### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by spkll** [SenticNet/MELD#1]
I am learning emotion recognition.So I downloaded your project,but the website of http://bit.ly/MELD-features that I can not enter.Can you send to my .And the others should I download,I can not enter either. Sincerely thank you .Email:982905429@qq.com

**Comment by SenticNet** [comment]
What problem did you encounter?

**Comment by spkll** [comment]
The following website I can not enter. Can you send them to me? Thank you so much!
http://bit.ly/MELD-raw and
http://bit.ly/MELD-features.

**Comment by SenticNet** [comment]
It is publicly available - https://drive.google.com/drive/folders/1y4nj9rBMHyEvfLNMcpoKsXm9cGdAcZpy?usp=sharing
