### ISSUE TITLE
Error in train.tar.gz

### ISSUE THREAD

**Issue by saxenarohit** [SenticNet/MELD#3]
Got this error while untar 

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

**Comment by SenticNet** [comment]
Ohh sorry to hear that. Can you please try to download it again from here - https://drive.google.com/drive/u/3/folders/1yY1jwWYPVZxAmIvc6uQ7-D-ZHOG7ctZ9

**Comment by SenticNet** [comment]
Let me know if you still face any error.
