### ISSUE TITLE
The meanings about the features.

### ISSUE THREAD

**Issue by XinyuLyu** [SenticNet/MELD#4]
![image](https://user-images.githubusercontent.com/33551398/47937418-0a6b8480-deb7-11e8-873f-fd233c505d04.png)
Can you exlpain what features each file represents？I'm a little confused about their file names. After reading the codes in basline.py and data_helper.py, you use cnn to extract the textual-features. Does it mean the vedio features? In your fusion model, I can't find the vedio branch.  And what does text_glove_average_emotion.pkl mean?  And what's the difference between audio_embeddings_feature_selection_emotion.pkl and audio_emotion.pkl?

**Comment by soujanyaporia** [comment]
text_glove_average_emotion.pkl -> initialise words with glove and then take average to represent a sentence
video -> we do not provide video features
audio_embeddings_feature_selection_emotion.pkl -> audio features after doing feature selection using PCA
