### ISSUE TITLE
missing training data

### ISSUE THREAD

**Issue by ChenJiaDong9219** [SenticNet/MELD#5]
Hi there, 
I've downloaded MELD.Raw.tar.gz, the dev and test data is ok, but the training data is missing.
when I untar train.tar.gz, it always shows the following issue:
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
and after that, I got 'split' directory which contains 4648 files. So I believe the training data is definitely missing.
I tried many times, always the same results.
I wish I can get some help with that.

**Comment by soujanyaporia** [comment]
Hi,

When did you download the training data?

**Comment by ChenJiaDong9219** [comment]
yesterday and a few days ago, I downloaded twice.

**Comment by soujanyaporia** [comment]
Here is an alternate link to download the data - 
https://drive.google.com/file/d/1LgBQDIUPmx0SiMOGKxM4v33ig9CSO_Ps/view?usp=sharing

**Comment by soujanyaporia** [comment]
Please use the alternate link above.

**Comment by ChenJiaDong9219** [comment]
thank you, I'm trying that now, I'll tell you the result asap the result comes out.

**Comment by ChenJiaDong9219** [comment]
thanks a lot, the training data is complete now!
