### ISSUE TITLE
About the sequence length and sentence length.

### ISSUE THREAD

**Issue by KuzmaNg** [SenticNet/MELD#6]
Hi, Meld crew. 
I tried running baseline code with text-only sentiment classification, and it worked. However, I got one question in _baseline_.py (Line 124). It's about the input_length in Embedding layer. I think it should be the sentence_length instead of the sequence_length, since the 2nd dimension of the _concatenated_tensor_ is a negative number (-48) in my case.

**Comment by devamanyu** [comment]
Hi. Thank you for noticing the error. We have now corrected the line!

**Comment by KuzmaNg** [comment]
@devamanyu  Thank you.
