### ISSUE TITLE
Failed to load pretrained models

### ISSUE THREAD

**Issue by KuzmaNg** [SenticNet/MELD#7]
Hi, 
I tried to reload the pretrained models, but failed. I assume it is a keras version problem. Would you like to describe the running enviroment? Sorry, I cannot find it in Readme.
Thanks.

**Comment by soujanyaporia** [comment]
What problem did you encounter? We used Keras > 2.0.2 and latest tf as a backend.

**Comment by KuzmaNg** [comment]
Thanks. @soujanyaporia 
The problem is, _unexpected keyword argument_ is found when reloading the pretrained model. I changed the keras to 2.1.5, and solved the problem. But I still cannot reproduce the result reported in paper MELD. Keep trying. : )

**Comment by soujanyaporia** [comment]
I guess you are not using class weights. Please do use class weights to reproduce the results. I think we will release it in next update.

**Comment by KuzmaNg** [comment]
Thank you for the hint. Aha
