### ISSUE TITLE
guidance for developing a LSTM model

### ISSUE THREAD

**Issue by Thani011** [SenticNet/MELD#8]
Hi,
I am struggling to find any support for developing a model for a multi-model dataset .
Can you please guide or give me some reference for using this dataset and developing a LSTM or CNN model.
I am new to this field but for now i am able to develop model for images and text separately but having trouble in using a merged input (image+text or image+audio ).

Please provide some direction or explain with respect to the baseline model you provided.
Thanks

**Comment by soujanyaporia** [comment]
Bimodal features have been provided in the repo. Please download and load using - 

import pickle
train_bimodal_emb, val_bimodal_emb, test_bimodal_emb = pickle.load(open(filepath, 'rb'))
